__author__ = 'dhana013'

import csv

buildProperties_list = [
  {
    "depName": "coastalBaseCloe",
    "depLoc": "M2_REPO",
    "client": "dv",
    "profile": "default",
    "projName": "dv-cloe",
    "branchName": "cloe-4_0_4_22_branch",
    "javaVersion": "jdk1.6.0_30",
    "tagHandler": "default",
    "failover-depLoc": "None"
  },
  {
    "depName": "tamBaseCloe",
    "depLoc": "M2_REPO",
    "client": "dv",
    "profile": "default",
    "projName": "cloe",
    "branchName": "master",
    "javaVersion": "jdk1.6.0_30",
    "tagHandler": "default",
    "failover-depLoc": "None"
  },
  {
    "depName": "rpBaseCloe",
    "depLoc": "M2_REPO",
    "client": "dv",
    "profile": "default",
    "projName": "dv-cloe-master",
    "branchName": "master",
    "javaVersion": "jdk1.6.0_30",
    "tagHandler": "default",
    "failover-depLoc": "None"
  },
  {
    "depName": "nysedmafo-22",
    "depLoc": "nysedmafo-22",
    "client": "fast-fo",
    "profile": "prod",
    "projName": "dv-cloe-algo-master",
    "branchName": "master",
    "javaVersion": "jdk1.6.0_30",
    "tagHandler": "default",
    "failover-depLoc": "None"
  },
  {
    "depName": "nysedmabeta-8",
    "depLoc": "nysedmabeta-8",
    "client": "fast-tpa",
    "profile": "beta",
    "projName": "dv-cloe-algo-master",
    "branchName": "master",
    "javaVersion": "jdk1.6.0_30",
    "tagHandler": "default",
    "failover-depLoc": "None"
  },
  {
    "depName": "nysedmaprod-90",
    "depLoc": "nysedmaprod-90",
    "client": "fast-fo",
    "profile": "dv.qa",
    "projName": "dv-cloe-algo-master",
    "branchName": "master",
    "javaVersion": "jdk1.6.0_30",
    "tagHandler": "default",
    "failover-depLoc": "None"
  },
  {
    "depName": "qa-rpfo24",
    "depLoc": "qa-rpfo24",
    "client": "fast-fo",
    "profile": "dv.qa",
    "projName": "dv-cloe-algo-master",
    "branchName": "cloe-algo-5.18_branch",
    "javaVersion": "jdk1.6.0_30",
    "tagHandler": "default",
    "failover-depLoc": "None"
  },
  {
    "depName": "qa-rpalgocluster69",
    "depLoc": "qa-rpalgocluster69",
    "client": "fast-tpa",
    "profile": "dv.qa",
    "projName": "dv-cloe-algo-master",
    "branchName": "cloe-algo-5.18_branch",
    "javaVersion": "jdk1.6.0_30",
    "tagHandler": "default",
    "failover-depLoc": "None"
  },
  {
    "depName": "ccapclusterqa-15",
    "depLoc": "ccapclusterqa-15",
    "client": "cap",
    "profile": "dv.qa",
    "projName": "dv-cloe-algo-master",
    "branchName": "master",
    "javaVersion": "jdk1.6.0_30",
    "tagHandler": "default",
    "failover-depLoc": "None"
  },
  {
    "depName": "ccapclientqa-79",
    "depLoc": "ccapclientqa-79",
    "client": "cap",
    "profile": "dv.qa",
    "projName": "dv-cloe-algo-master",
    "branchName": "master",
    "javaVersion": "jdk1.6.0_30",
    "tagHandler": "default",
    "failover-depLoc": "None"
  },
  {
    "depName": "ccapclientqa-9",
    "depLoc": "ccapclientqa-9",
    "client": "cap",
    "profile": "dv.qa",
    "projName": "dv-cloe-algo-master",
    "branchName": "master",
    "javaVersion": "jdk1.6.0_30",
    "tagHandler": "default",
    "failover-depLoc": "None"
  },
  {
    "depName": "kratosdvqa10",
    "depLoc": "kratosdvqa10",
    "client": "kratos",
    "profile": "dv.qa",
    "projName": "dv-cloe",
    "branchName": "cloe-3_3_0_branch",
    "javaVersion": "jdk1.6.0_30",
    "tagHandler": "default",
    "failover-depLoc": "None"
  },
  {
    "depName": "krouterdvqa10",
    "depLoc": "krouterdvqa10",
    "client": "krouter",
    "profile": "dv.qa",
    "projName": "dv-cloe",
    "branchName": "cloe-3_3_0_branch",
    "javaVersion": "jdk1.6.0_30",
    "tagHandler": "default",
    "failover-depLoc": "None"
  },
  {
    "depName": "stdkrouterprod6",
    "depLoc": "stdkrouterprod6",
    "client": "krouter",
    "profile": "dv.qa",
    "projName": "dv-cloe",
    "branchName": "cloe-3.3.0.121_branch",
    "javaVersion": "jdk1.6.0_30",
    "tagHandler": "default",
    "failover-depLoc": "None"
  },
  {
    "depName": "stdkratosprod9",
    "depLoc": "stdkratosprod9",
    "client": "kratos",
    "profile": "dv.qa",
    "projName": "dv-cloe",
    "branchName": "cloe-3_3_0_branch",
    "javaVersion": "jdk1.6.0_30",
    "tagHandler": "default",
    "failover-depLoc": "None"
  },
  {
    "depName": "stdkratosbeta84",
    "depLoc": "stdkratosbeta84",
    "client": "kratos",
    "profile": "dv.qa",
    "projName": "dv-cloe",
    "branchName": "cloe-3.3.0.121_branch",
    "javaVersion": "jdk1.6.0_30",
    "tagHandler": "default",
    "failover-depLoc": "None"
  },
  {
    "depName": "ceresclusterqa-223",
    "depLoc": "ceresclusterqa-223",
    "client": "ceres",
    "profile": "dv.qa",
    "projName": "cloe-algo",
    "branchName": "master",
    "javaVersion": "jdk1.6.0_30",
    "tagHandler": "default",
    "failover-depLoc": "None"
  },
  {
    "depName": "qa-cos4algo93",
    "depLoc": "qa-cos4algo93",
    "client": "coastal",
    "profile": "dv.qa",
    "projName": "dv-cloe-algo",
    "branchName": "cloe-algo-1_1_5_branch",
    "javaVersion": "jdk1.6.0_30",
    "tagHandler": "default",
    "failover-depLoc": "None"
  },
  {
    "depName": "qa-rpalgocluster32",
    "depLoc": "qa-rpalgocluster32",
    "client": "fast-tpa",
    "profile": "dv.qa",
    "projName": "dv-cloe-algo-master",
    "branchName": "master",
    "javaVersion": "jdk1.6.0_30",
    "tagHandler": "default",
    "failover-depLoc": "None"
  },
  {
    "depName": "qa-rpalgoclusterqa15",
    "depLoc": "qa-rpalgoclusterqa15",
    "client": "fast-tpa",
    "profile": "dv.qa",
    "projName": "dv-cloe-algo-master",
    "branchName": "master",
    "javaVersion": "jdk1.6.0_30",
    "tagHandler": "default",
    "failover-depLoc": "None"
  },
  {
    "depName": "qa-rpalgoclusterqa55",
    "depLoc": "qa-rpalgoclusterqa55",
    "client": "fast-tpa",
    "profile": "dv.qa",
    "projName": "dv-cloe-algo-master",
    "branchName": "master",
    "javaVersion": "jdk1.6.0_30",
    "tagHandler": "default",
    "failover-depLoc": "None"
  },
  {
    "depName": "qa-rpalgocluster80",
    "depLoc": "qa-rpalgocluster80",
    "client": "fast-tpa",
    "profile": "dv.qa",
    "projName": "dv-cloe-algo-master",
    "branchName": "master",
    "javaVersion": "jdk1.6.0_30",
    "tagHandler": "default",
    "failover-depLoc": "None"
  },
  {
    "depName": "qa-rpfo27",
    "depLoc": "qa-rpfo27",
    "client": "fast-fo",
    "profile": "dv.qa",
    "projName": "dv-cloe-algo-master",
    "branchName": "master",
    "javaVersion": "jdk1.6.0_30",
    "tagHandler": "default",
    "failover-depLoc": "None"
  },
  {
    "depName": "qa-rpfoqa69",
    "depLoc": "qa-rpfoqa69",
    "client": "fast-fo",
    "profile": "dv.qa",
    "projName": "dv-cloe-algo-master",
    "branchName": "master",
    "javaVersion": "jdk1.6.0_30",
    "tagHandler": "default",
    "failover-depLoc": "None"
  },
  {
    "depName": "qa-rpfoqa38",
    "depLoc": "qa-rpfoqa38",
    "client": "fast-fo",
    "profile": "dv.qa",
    "projName": "dv-cloe-algo-master",
    "branchName": "master",
    "javaVersion": "jdk1.6.0_30",
    "tagHandler": "default",
    "failover-depLoc": "None"
  },
  {
    "depName": "qa-rpfo77",
    "depLoc": "qa-rpfo77",
    "client": "fast-fo",
    "profile": "dv.qa",
    "projName": "dv-cloe-algo-master",
    "branchName": "master",
    "javaVersion": "jdk1.6.0_30",
    "tagHandler": "default",
    "failover-depLoc": "None"
  },
  {
    "depName": "qa-rpfo33",
    "depLoc": "qa-rpfo33",
    "client": "fast-fo",
    "profile": "dv.qa",
    "projName": "dv-cloe-algo-master",
    "branchName": "master",
    "javaVersion": "jdk1.6.0_30",
    "tagHandler": "default",
    "failover-depLoc": "None"
  },
  {
    "depName": "qa-dropcopy77",
    "depLoc": "qa-dropcopy77",
    "client": "coastal",
    "profile": "prod.dc",
    "projName": "dv-cloe-algo-master",
    "branchName": "master",
    "javaVersion": "jdk1.6.0_30",
    "tagHandler": "default",
    "failover-depLoc": "None"
  },
  {
    "depName": "kratosdvqa64",
    "depLoc": "kratosdvqa64",
    "client": "kratos",
    "profile": "dv.qa",
    "projName": "dv-cloe",
    "branchName": "cloe-3_3_0_branch",
    "javaVersion": "jdk1.6.0_30",
    "tagHandler": "default",
    "failover-depLoc": "None"
  },
  {
    "depName": "kratosdvqa26",
    "depLoc": "kratosdvqa26",
    "client": "kratos",
    "profile": "dv.qa",
    "projName": "dv-cloe",
    "branchName": "cloe-3_3_0_branch",
    "javaVersion": "jdk1.6.0_30",
    "tagHandler": "default",
    "failover-depLoc": "None"
  },
  {
    "depName": "krouterdvqa21",
    "depLoc": "krouterdvqa21",
    "client": "krouter",
    "profile": "dv.qa",
    "projName": "dv-cloe",
    "branchName": "cloe-3_3_0_branch",
    "javaVersion": "jdk1.6.0_30",
    "tagHandler": "default",
    "failover-depLoc": "None"
  },
  {
    "depName": "krouterdvqa63",
    "depLoc": "krouterdvqa63",
    "client": "krouter",
    "profile": "dv.qa",
    "projName": "dv-cloe",
    "branchName": "cloe-3_3_0_branch",
    "javaVersion": "jdk1.6.0_30",
    "tagHandler": "default",
    "failover-depLoc": "None"
  },
  {
    "depName": "kratosdvqa75",
    "depLoc": "kratosdvqa75",
    "client": "kratos",
    "profile": "dv.qa",
    "projName": "dv-cloe",
    "branchName": "cloe-3.3.0.121_branch",
    "javaVersion": "jdk1.6.0_30",
    "tagHandler": "default",
    "failover-depLoc": "None"
  },
  {
    "depName": "krouterdvqa74",
    "depLoc": "krouterdvqa74",
    "client": "krouter",
    "profile": "dv.qa",
    "projName": "dv-cloe",
    "branchName": "cloe-3.3.0.121_branch",
    "javaVersion": "jdk1.6.0_30",
    "tagHandler": "default",
    "failover-depLoc": "None"
  },
  {
    "depName": "kratosdvqa15",
    "depLoc": "kratosdvqa15",
    "client": "kratos",
    "profile": "dv.qa",
    "projName": "dv-cloe",
    "branchName": "cloe-3_3_0_branch",
    "javaVersion": "jdk1.6.0_30",
    "tagHandler": "default",
    "failover-depLoc": "None"
  },
  {
    "depName": "krouterdvqa79",
    "depLoc": "krouterdvqa79",
    "client": "krouter",
    "profile": "dv.qa",
    "projName": "dv-cloe",
    "branchName": "cloe-3_3_0_branch",
    "javaVersion": "jdk1.6.0_30",
    "tagHandler": "default",
    "failover-depLoc": "None"
  },
  {
    "depName": "stdkratosdvqa75",
    "depLoc": "stdkratosdvqa75",
    "client": "kratos",
    "profile": "dv.qa",
    "projName": "dv-cloe",
    "branchName": "cloe-3.3.0.121_branch",
    "javaVersion": "jdk1.6.0_30",
    "tagHandler": "default",
    "failover-depLoc": "None"
  },
  {
    "depName": "stdkrouterdvqa74",
    "depLoc": "stdkrouterdvqa74",
    "client": "krouter",
    "profile": "dv.qa",
    "projName": "dv-cloe",
    "branchName": "cloe-3.3.0.121_branch",
    "javaVersion": "jdk1.6.0_30",
    "tagHandler": "default",
    "failover-depLoc": "None"
  },
  {
    "depName": "kratosdvqa8",
    "depLoc": "kratosdvqa8",
    "client": "kratos",
    "profile": "dv.qa",
    "projName": "dv-cloe",
    "branchName": "cloe-3_3_0_branch",
    "javaVersion": "jdk1.6.0_30",
    "tagHandler": "default",
    "failover-depLoc": "None"
  },
  {
    "depName": "kratosclusterqa40",
    "depLoc": "kratosclusterqa40",
    "client": "kratos",
    "profile": "cluster.qa",
    "projName": "dv-cloe",
    "branchName": "cloe-3_3_0_branch",
    "javaVersion": "jdk1.6.0_30",
    "tagHandler": "default",
    "failover-depLoc": "None"
  },
  {
    "depName": "kratosBeta82",
    "depLoc": "kratosBeta82",
    "client": "kratos",
    "profile": "beta",
    "projName": "dv-cloe",
    "branchName": "cloe-3_3_0_branch",
    "javaVersion": "jdk1.6.0_30",
    "tagHandler": "default",
    "failover-depLoc": "beta-kratosfailover"
  },
  {
    "depName": "kratosProd5",
    "depLoc": "kratosProd5",
    "client": "kratos",
    "profile": "prod",
    "projName": "dv-cloe",
    "branchName": "cloe-3_3_0_branch",
    "javaVersion": "jdk1.6.0_30",
    "tagHandler": "default",
    "failover-depLoc": "None"
  },
  {
    "depName": "kratosprebeta35",
    "depLoc": "kratosprebeta35",
    "client": "kratos",
    "profile": "beta.alpha",
    "projName": "dv-cloe",
    "branchName": "cloe-3_3_0_branch",
    "javaVersion": "jdk1.6.0_30",
    "tagHandler": "default",
    "failover-depLoc": "None"
  },
  {
    "depName": "prod-krouterfailover",
    "depLoc": "prod-krouterfailover",
    "client": "krouter",
    "profile": "dv.qa",
    "projName": "dv-cloe",
    "branchName": "cloe-3_3_0_branch",
    "javaVersion": "jdk1.6.0_30",
    "tagHandler": "default",
    "failover-depLoc": "None"
  },
  {
    "depName": "prod-kratosfailover",
    "depLoc": "prod-kratosfailover",
    "client": "kratos",
    "profile": "dv.qa",
    "projName": "dv-cloe",
    "branchName": "cloe-3_3_0_branch",
    "javaVersion": "jdk1.6.0_30",
    "tagHandler": "default",
    "failover-depLoc": "None"
  },
  {
    "depName": "beta-kratosfailover",
    "depLoc": "beta-kratosfailover",
    "client": "kratos",
    "profile": "failover.beta",
    "projName": "dv-cloe",
    "branchName": "cloe-3_3_0_branch",
    "javaVersion": "jdk1.6.0_30",
    "tagHandler": "default",
    "failover-depLoc": "None"
  },
  {
    "depName": "dmafoprod34",
    "depLoc": "dmafoprod34",
    "client": "fast-fo",
    "profile": "dv.qa",
    "projName": "dv-cloe-algo-master",
    "branchName": "master",
    "javaVersion": "jdk1.6.0_30",
    "tagHandler": "default",
    "failover-depLoc": "None"
  },
  {
    "depName": "dmaalgoprod63",
    "depLoc": "dmaalgoprod63",
    "client": "fast-tpa",
    "profile": "dv.qa",
    "projName": "dv-cloe-algo-master",
    "branchName": "master",
    "javaVersion": "jdk1.6.0_30",
    "tagHandler": "default",
    "failover-depLoc": "None"
  },
  {
    "depName": "dmaalgobeta35",
    "depLoc": "dmaalgobeta35",
    "client": "fast-tpa",
    "profile": "dv.qa",
    "projName": "dv-cloe-algo-master",
    "branchName": "master",
    "javaVersion": "jdk1.6.0_30",
    "tagHandler": "default",
    "failover-depLoc": "None"
  },
  {
    "depName": "qa-krouterdvqa72",
    "depLoc": "qa-krouterdvqa72",
    "client": "krouter",
    "profile": "dv.qa",
    "projName": "dv-cloe",
    "branchName": "cloe-3_3_0_branch",
    "javaVersion": "jdk1.6.0_30",
    "tagHandler": "default",
    "failover-depLoc": "None"
  },
  {
    "depName": "cloekrouterqa-23",
    "depLoc": "cloekrouterqa-23",
    "client": "krouter",
    "profile": "dv.qa",
    "projName": "dv-cloe",
    "branchName": "cloe-3_3_0_branch",
    "javaVersion": "jdk1.6.0_30",
    "tagHandler": "default",
    "failover-depLoc": "None"
  },
  {
    "depName": "krouterprod7",
    "depLoc": "krouterprod7",
    "client": "krouter",
    "profile": "prod",
    "projName": "dv-cloe",
    "branchName": "cloe-3_3_0_branch",
    "javaVersion": "jdk1.6.0_30",
    "tagHandler": "default",
    "failover-depLoc": "None"
  },
  {
    "depName": "qa-cos4algo15",
    "depLoc": "qa-cos4algo15",
    "client": "coastal",
    "profile": "dv.qa",
    "projName": "dv-cloe-algo",
    "branchName": "cloe-algo-1_1_5_22_branch",
    "javaVersion": "jdk1.6.0_30",
    "tagHandler": "default",
    "failover-depLoc": "None"
  },
  {
    "depName": "beta-coastal",
    "depLoc": "beta-coastal",
    "client": "coastal",
    "profile": "beta",
    "projName": "dv-cloe-algo",
    "branchName": "cloe-algo-1_1_5_22_branch",
    "javaVersion": "jdk1.6.0_30",
    "tagHandler": "default",
    "failover-depLoc": "None"
  },
  {
    "depName": "qa-crisisreport",
    "depLoc": "qa-crisisreport",
    "client": "dv",
    "profile": "default",
    "projName": "crisisreport",
    "branchName": "master",
    "javaVersion": "jdk1.6.0_30",
    "tagHandler": "default",
    "failover-depLoc": "None"
  },
  {
    "depName": "dvHbase",
    "depLoc": "dvHbase-repo",
    "client": "dv",
    "profile": "default",
    "projName": "dvHbase",
    "branchName": "master",
    "javaVersion": "jdk1.6.0_30",
    "tagHandler": "default",
    "failover-depLoc": "None"
  },
  {
    "depName": "oatsprod",
    "depLoc": "oatspros",
    "client": "oats",
    "profile": "default",
    "projName": "oats",
    "branchName": "oats-1_0_branch",
    "javaVersion": "jdk1.6.0_30",
    "tagHandler": "default",
    "failover-depLoc": "None"
  },
  {
    "depName": "oatsprod_tpa",
    "depLoc": "oatsprod_tpa",
    "client": "oats",
    "profile": "default",
    "projName": "oats",
    "branchName": "oats-1_0_3_branch",
    "javaVersion": "jdk1.6.0_30",
    "tagHandler": "default",
    "failover-depLoc": "None"
  },
  {
    "depName": "oatsprod_fast",
    "depLoc": "oatsprod_fast",
    "client": "oats",
    "profile": "default",
    "projName": "oats",
    "branchName": "rp-client-1_0_4_branch",
    "javaVersion": "jdk1.6.0_30",
    "tagHandler": "default",
    "failover-depLoc": "None"
  },
  {
    "depName": "prod-rebateManager",
    "depLoc": "prod-rebateManager",
    "client": "dv",
    "profile": "default",
    "projName": "rebatemanager",
    "branchName": "master",
    "javaVersion": "jdk1.6.0_30",
    "tagHandler": "default",
    "failover-depLoc": "None"
  },
  {
    "depName": "prod-releasediary",
    "depLoc": "prod-releasediary",
    "client": "dv",
    "profile": "default",
    "projName": "releasediary",
    "branchName": "master",
    "javaVersion": "jdk1.6.0_30",
    "tagHandler": "default",
    "failover-depLoc": "None"
  },
  {
    "depName": "prod-salus",
    "depLoc": "prod-salus",
    "client": "dv",
    "profile": "default",
    "projName": "salus",
    "branchName": "master",
    "javaVersion": "jdk1.6.0_30",
    "tagHandler": "default",
    "failover-depLoc": "None"
  },
  {
    "depName": "prod-crisisreport",
    "depLoc": "prod-crisisreport",
    "client": "dv",
    "profile": "default",
    "projName": "crisisreport",
    "branchName": "master",
    "javaVersion": "jdk1.6.0_30",
    "tagHandler": "default",
    "failover-depLoc": "None"
  },
  {
    "depName": "prod-dailydiary",
    "depLoc": "prod-dailydiary",
    "client": "dv",
    "profile": "default",
    "projName": "dailydiary",
    "branchName": "master",
    "javaVersion": "jdk1.6.0_30",
    "tagHandler": "default",
    "failover-depLoc": "None"
  },
  {
    "depName": "prod-narita",
    "depLoc": "prod-narita",
    "client": "dv",
    "profile": "default",
    "projName": "narita",
    "branchName": "master",
    "javaVersion": "jdk1.6.0_30",
    "tagHandler": "default",
    "failover-depLoc": "None"
  },
  {
    "depName": "prod-naritafast",
    "depLoc": "prod-naritafast",
    "client": "dv",
    "profile": "default",
    "projName": "narita",
    "branchName": "master",
    "javaVersion": "jdk1.6.0_30",
    "tagHandler": "default",
    "failover-depLoc": "None"
  },
  {
    "depName": "dvis-build",
    "depLoc": "dvis-build",
    "client": "dv",
    "profile": "default",
    "projName": "dvis",
    "branchName": "master",
    "javaVersion": "jdk1.6.0_30",
    "tagHandler": "default",
    "failover-depLoc": "None"
  },
  {
    "depName": "clio-build",
    "depLoc": "clio-build",
    "client": "dv",
    "profile": "default",
    "projName": "clio",
    "branchName": "master",
    "javaVersion": "jdk1.6.0_30",
    "tagHandler": "default",
    "failover-depLoc": "None"
  },
  {
    "depName": "prod-athena",
    "depLoc": "None",
    "client": "None",
    "profile": "None",
    "projName": "None",
    "branchName": "None",
    "javaVersion": "None",
    "tagHandler": "None",
    "failover-depLoc": "None"
  },
  {
    "depName": "prod-dvversion",
    "depLoc": "None",
    "client": "None",
    "profile": "None",
    "projName": "None",
    "branchName": "None",
    "javaVersion": "None",
    "tagHandler": "None",
    "failover-depLoc": "None"
  },
  {
    "depName": "prod-emitscope",
    "depLoc": "None",
    "client": "None",
    "profile": "None",
    "projName": "None",
    "branchName": "None",
    "javaVersion": "None",
    "tagHandler": "None",
    "failover-depLoc": "None"
  },
  {
    "depName": "prod-iris",
    "depLoc": "None",
    "client": "None",
    "profile": "None",
    "projName": "None",
    "branchName": "None",
    "javaVersion": "None",
    "tagHandler": "None",
    "failover-depLoc": "None"
  },
  {
    "depName": "prod-pandora",
    "depLoc": "None",
    "client": "None",
    "profile": "None",
    "projName": "None",
    "branchName": "None",
    "javaVersion": "None",
    "tagHandler": "None",
    "failover-depLoc": "None"
  },
  {
    "depName": "prod-plutus",
    "depLoc": "None",
    "client": "None",
    "profile": "None",
    "projName": "None",
    "branchName": "None",
    "javaVersion": "None",
    "tagHandler": "None",
    "failover-depLoc": "None"
  },
  {
    "depName": "prod-ptsviz",
    "depLoc": "None",
    "client": "None",
    "profile": "None",
    "projName": "None",
    "branchName": "None",
    "javaVersion": "None",
    "tagHandler": "None",
    "failover-depLoc": "None"
  },
  {
    "depName": "prod-simviz",
    "depLoc": "None",
    "client": "None",
    "profile": "None",
    "projName": "None",
    "branchName": "None",
    "javaVersion": "None",
    "tagHandler": "None",
    "failover-depLoc": "None"
  },
  {
    "depName": "prod-testtracker",
    "depLoc": "None",
    "client": "None",
    "profile": "None",
    "projName": "None",
    "branchName": "None",
    "javaVersion": "None",
    "tagHandler": "None",
    "failover-depLoc": "None"
  },
  {
    "depName": "prod-themis",
    "depLoc": "None",
    "client": "None",
    "profile": "None",
    "projName": "None",
    "branchName": "None",
    "javaVersion": "None",
    "tagHandler": "None",
    "failover-depLoc": "None"
  },
  {
    "depName": "qa-athena",
    "depLoc": "None",
    "client": "None",
    "profile": "None",
    "projName": "None",
    "branchName": "None",
    "javaVersion": "None",
    "tagHandler": "None",
    "failover-depLoc": "None"
  },
  {
    "depName": "qa-dvversion",
    "depLoc": "None",
    "client": "None",
    "profile": "None",
    "projName": "None",
    "branchName": "None",
    "javaVersion": "None",
    "tagHandler": "None",
    "failover-depLoc": "None"
  },
  {
    "depName": "qa-emitscope",
    "depLoc": "None",
    "client": "None",
    "profile": "None",
    "projName": "None",
    "branchName": "None",
    "javaVersion": "None",
    "tagHandler": "None",
    "failover-depLoc": "None"
  },
  {
    "depName": "qa-iris",
    "depLoc": "None",
    "client": "None",
    "profile": "None",
    "projName": "None",
    "branchName": "None",
    "javaVersion": "None",
    "tagHandler": "None",
    "failover-depLoc": "None"
  },
  {
    "depName": "qa-leto",
    "depLoc": "None",
    "client": "None",
    "profile": "None",
    "projName": "None",
    "branchName": "None",
    "javaVersion": "None",
    "tagHandler": "None",
    "failover-depLoc": "None"
  },
  {
    "depName": "qa-narita",
    "depLoc": "qa-narita",
    "client": "dv",
    "profile": "default",
    "projName": "narita",
    "branchName": "master",
    "javaVersion": "jdk1.6.0_30",
    "tagHandler": "default",
    "failover-depLoc": "None"
  },
  {
    "depName": "qa-narita-fast",
    "depLoc": "qa-narita-fast",
    "client": "dv",
    "profile": "default",
    "projName": "narita",
    "branchName": "master",
    "javaVersion": "jdk1.6.0_30",
    "tagHandler": "default",
    "failover-depLoc": "None"
  },
  {
    "depName": "qa-sprywaredatarecorder",
    "depLoc": "qa-sprywaredatarecorder",
    "client": "dv",
    "profile": "default",
    "projName": "sprywaredatarecorder",
    "branchName": "master",
    "javaVersion": "jdk1.6.0_30",
    "tagHandler": "default",
    "failover-depLoc": "None"
  },
  {
    "depName": "qa-pandora",
    "depLoc": "None",
    "client": "None",
    "profile": "None",
    "projName": "None",
    "branchName": "None",
    "javaVersion": "None",
    "tagHandler": "None",
    "failover-depLoc": "None"
  },
  {
    "depName": "qa-plutus",
    "depLoc": "None",
    "client": "None",
    "profile": "None",
    "projName": "None",
    "branchName": "None",
    "javaVersion": "None",
    "tagHandler": "None",
    "failover-depLoc": "None"
  },
  {
    "depName": "qa-ptsviz",
    "depLoc": "None",
    "client": "None",
    "profile": "None",
    "projName": "None",
    "branchName": "None",
    "javaVersion": "None",
    "tagHandler": "None",
    "failover-depLoc": "None"
  },
  {
    "depName": "qa-rebateManager",
    "depLoc": "None",
    "client": "None",
    "profile": "None",
    "projName": "None",
    "branchName": "None",
    "javaVersion": "None",
    "tagHandler": "None",
    "failover-depLoc": "None"
  },
  {
    "depName": "qa-rhea",
    "depLoc": "None",
    "client": "None",
    "profile": "None",
    "projName": "None",
    "branchName": "None",
    "javaVersion": "None",
    "tagHandler": "None",
    "failover-depLoc": "None"
  },
  {
    "depName": "qa-salus",
    "depLoc": "qa-salus",
    "client": "dv",
    "profile": "default",
    "projName": "salus",
    "branchName": "master",
    "javaVersion": "jdk1.6.0_30",
    "tagHandler": "default",
    "failover-depLoc": "None"
  },
  {
    "depName": "qa-simviz",
    "depLoc": "None",
    "client": "None",
    "profile": "None",
    "projName": "None",
    "branchName": "None",
    "javaVersion": "None",
    "tagHandler": "None",
    "failover-depLoc": "None"
  },
  {
    "depName": "qa-testtracker",
    "depLoc": "None",
    "client": "None",
    "profile": "None",
    "projName": "None",
    "branchName": "None",
    "javaVersion": "None",
    "tagHandler": "None",
    "failover-depLoc": "None"
  }
]


buildProperties_temp = []
buildProperties_dict = {}

for x in buildProperties_list:
    buildProperties_temp.append({x['depName']:x})

print buildProperties_temp